/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'ajayshi' at '1/4/17 4:36 PM' with Gradle 2.9
 *
 * @author ajayshi, @date 1/4/17 4:36 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
